SpeedInvoices.Web/Controllers/ClientDashController.cs
using Newtonsoft.Json;
using Rotativa;
using SpeedInvoices.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SpeedInvoices.Web.Controllers
{
    public class ClientDashController : Controller
    {
        string LienClientApi = "http://localhost:81/SpeedInvoices.Service/api/Client";
        string LienFactureApi = "http://localhost:81/SpeedInvoices.Service/api/Facture";
        string LienApiCompte = "http://localhost:81/SpeedInvoices.Service/api/Structure";
        string LienProduit_FactureApi = "http://localhost:81/SpeedInvoices.Service/api/Produit_Facture";
        string LienProduitApi = "http://localhost:81/SpeedInvoices.Service/api/Produit";
        string LienEtatApi = "http://localhost:81/SpeedInvoices.Service/api/Etat";
        static ClientModel clientStatic;
        // GET: ClientDash
        public async Task<ActionResult> Index()
        {
            IndexClientModel model = new IndexClientModel();
            ClientModel clientt = clientStatic;
            //Compter nombre de facture non soldée
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<FactureModel> factureNS = new List<FactureModel>();
                var response = await client.GetAsync(LienFactureApi + "?IdClient=" + clientt.IdClient + "&IdEtat=" + 2);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    factureNS = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
                model.NombreFNS = factureNS.Count();
            }

            //Compter nombre de facture soldée
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<FactureModel> factureS = new List<FactureModel>();
                var response = await client.GetAsync(LienFactureApi + "?IdClient=" + clientt.IdClient + "&IdEtat=" + 3);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    factureS = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
                model.NombreFS = factureS.Count();
            }

            //Calcul des pourcentages
            model.Pfns = model.NombreFNS;
            model.Pfs = model.NombreFS;

            //Structure
            model.NomClient = clientt.NomClient;
            model.PrenomClient = clientStatic.PrenomClient;
            model.AdresseClient = clientt.AdresseClient;
            model.TelephoneClient = clientt.TelephoneClient;
            model.Email = clientt.Email;

            return View(model);
        }

        public async Task<ActionResult> FactureS()
        {
            int IdEtat = 2;
            IEnumerable<FactureModel> model = new List<FactureModel>();
            
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(LienFactureApi + "?IdClient=" + clientStatic.IdClient + "&IdEtat=" + IdEtat);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
            }
            return View(model);
        }

        public async Task<ActionResult> FactureNS()
        {
            int IdEtat = 3;
            IEnumerable<FactureModel> model = new List<FactureModel>();
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(LienFactureApi + "?IdClient=" + clientStatic.IdClient + "&IdEtat=" + IdEtat);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
            }
            return View(model);
        }


        public ActionResult Login(string returnUrl)
        {
            ClientModel c = clientStatic;
            if (c != null)
            {
                return RedirectToAction("Index");
            }
            return View(new ClientModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<ActionResult> Login(ClientModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    IList<StructureModel> structures = new List<StructureModel>();
                    using (HttpClient client = new HttpClient())
                    {
                        var response = await client.GetAsync(LienApiCompte);
                        if (response.IsSuccessStatusCode)
                        {
                            var json = await response.Content.ReadAsStringAsync();
                            structures = JsonConvert.DeserializeObject<IList<StructureModel>>(json);
                        }
                    }

                    IEnumerable<ClientModel> models = new List<ClientModel>();
                    using (HttpClient client = new HttpClient())
                    {
                        var response = await client.GetAsync(LienClientApi);
                        if (response.IsSuccessStatusCode)
                        {
                            var json = await response.Content.ReadAsStringAsync();
                            models = JsonConvert.DeserializeObject<IEnumerable<ClientModel>>(json);
                        }
                    }

                    foreach (var m in models)
                    {
                        if (m.Email.ToLower().Equals(model.Email, StringComparison.OrdinalIgnoreCase))
                        {
                            if (m.MotDePasse.Equals(model.MotDePasse, StringComparison.OrdinalIgnoreCase))
                            {
                                foreach(var s in structures)
                                {
                                    if(m.IdStructure == s.IdStructure)
                                    {
                                        Session["Client"] = m;
                                        Session["IdClient"] = m.IdClient;
                                        Session["NomClient"] = m.NomClient + " " + m.PrenomClient;
                                        m.Structure = s;
                                        clientStatic = m;
                                        return RedirectToAction("Index");
                                    }
                                }
                                
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            model.IsError = true;
            model.Message = "Email ou mot de passe invalide !";
            return View(model);
        }

        public ActionResult Forgot()
        {
            ClientModel model = new ClientModel();
            model.Message = null;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Forgotten(ClientModel model)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<ClientModel> models = new List<ClientModel>();
                using (HttpClient client = new HttpClient())
                {
                    var response = await client.GetAsync(LienClientApi);
                    if (response.IsSuccessStatusCode)
                    {
                        var json = await response.Content.ReadAsStringAsync();
                        models = JsonConvert.DeserializeObject<IEnumerable<ClientModel>>(json);
                    }
                }

                foreach (var m in models)
                {
                    if (m.Email.ToLower().Equals(model.Email, StringComparison.OrdinalIgnoreCase))
                    {
                        return View("ForgotOK");
                    }
                }
            }
            model.IsError = true;
            model.Message = "Cet email n'existe pas !";
            return View("Forgot", model);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Accueil", "Accueil");
        }

        public ActionResult Parametre()
        {
            ClientModel model = clientStatic;
            model.MotDePasse = null;
            return View(model);
        }

        [HttpPost]
        // Ne marche pas !! ca ne change pas le mot de passe.
        public async Task<ActionResult> Changer(ClientModel model)
        {
            try
            {
                ClientModel clientModel = clientStatic;
                model = clientModel;
                if (ModelState.IsValid)
                {
                    using (HttpClient client = new HttpClient())
                    {
                        HttpResponseMessage response = await client.GetAsync(LienClientApi + "?IdClient" + model.IdClient + "&NMotDePasse=" + model.NMotDePasse);

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index");
                        else
                            ModelState.AddModelError("", await response.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View("Parametre", model);
        }

        public async Task<ActionResult> Details(int id)
        {

SpeedInvoices.Web/Controllers/StructureController.cs
using Newtonsoft.Json;
using SpeedInvoices.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SpeedInvoices.Web.Controllers
{
    public class StructureController : Controller
    {
        string LienApiCompte = "http://localhost:81/SpeedInvoices.Service/api/Structure";
        // GET: Compte
        public ActionResult Login(string returnUrl)
        {
            StructureModel s = (StructureModel)Session["utilisateur"];
            if ( s != null)
            {
                return RedirectToAction("Index", "Gestion");
            }
            return View(new StructureModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<ActionResult> Login(StructureModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    IEnumerable<StructureModel> models = new List<StructureModel>();
                    using (HttpClient client = new HttpClient())
                    {
                        var response = await client.GetAsync(LienApiCompte);
                        if (response.IsSuccessStatusCode)
                        {
                            var json = await response.Content.ReadAsStringAsync();
                            models = JsonConvert.DeserializeObject<IEnumerable<StructureModel>>(json);
                        }
                    }

                    foreach(var m in models)
                    {
                        if (m.Email.ToLower().Equals(model.Email, StringComparison.OrdinalIgnoreCase))
                        {
                            if (m.MotDePasse.Equals(model.MotDePasse, StringComparison.OrdinalIgnoreCase))
                            {
                                Session["utilisateur"] = m;
                                Session["id"] = m.IdStructure;
                                Session["nom"] = m.NomStructure;
                                Session["LogoStructure"] = m.LogoStructure;
                                return RedirectToAction("Index", "Gestion");
                            }
                        }
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            model.IsError = true;
            model.Message = "Email ou mot de passe invalide !";
            return View(model);
        }

        public ActionResult Register(string returnUrl)
        {
            return View(new StructureModel { ReturnUrl = returnUrl });
        }

        [HttpPost]
        public async Task<ActionResult> Register(StructureModel model)
        {
            try
            {
                MultipartFormDataContent multipart = new MultipartFormDataContent();

                if (ModelState.IsValid)
                {
                    model.DateCreationStructure = DateTime.Now;
                    var json = JsonConvert.SerializeObject(model);
                    StringContent content = new StringContent
                    (
                        json,
                        Encoding.UTF8,
                        "application/json"
                    );

                    multipart.Add(content, "data");

                    if (model.Image.ContentLength > 0)
                    {
                        byte[] picture = new byte[model.Image.ContentLength];
                        model.Image.InputStream.Read(picture, 0, picture.Length);
                        ByteArrayContent byteContent = new ByteArrayContent(picture);
                        multipart.Add(byteContent, "picture", model.Image.FileName);
                    }

                    using (HttpClient client = new HttpClient())
                    {
                        HttpResponseMessage response = await client.PostAsync(LienApiCompte, multipart);
                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Login");
                        else
                            ModelState.AddModelError("", await response.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(model);
        }

        public ActionResult Forgot()
        {
            StructureModel model = new StructureModel();
            model.Message = null;
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Forgotten(StructureModel model)
        {
            if (ModelState.IsValid)
            {
                IEnumerable<StructureModel> models = new List<StructureModel>();
                using (HttpClient client = new HttpClient())
                {
                    var response = await client.GetAsync(LienApiCompte);
                    if (response.IsSuccessStatusCode)
                    {
                        var json = await response.Content.ReadAsStringAsync();
                        models = JsonConvert.DeserializeObject<IEnumerable<StructureModel>>(json);
                    }
                }

                foreach (var m in models)
                {
                    if (m.Email.ToLower().Equals(model.Email, StringComparison.OrdinalIgnoreCase))
                    {
                        return View("ForgotOK");
                    }
                }
            }
            model.IsError = true;
            model.Message = "Cet email n'existe pas !";
            return View("Forgot", model);
        }

        public ActionResult Logout()
        {
            Session.Clear();
            return RedirectToAction("Index", "Accueil", "Accueil");
        }

        public ActionResult About()
        {
            return RedirectToAction("Index", "Accueil", "Accueil");
        }
    }
}

SpeedInvoices.Web/Views/ClientDash/FactureNS.cshtml
@model IEnumerable<SpeedInvoices.Web.Models.FactureModel>

@{
    ViewBag.Title = "Liste de facture non soldée";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReferenceFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreationFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontantTtcFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Etat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Structure)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReferenceFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreationFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontantTtcFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Etat.NomEtat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Structure.NomStructure)
        </td>
        <td>
            <a href="@Url.Action("Details", "ClientDash", new { id = item.IdFacture })" class="btn btn-primary">
                <i class="bi bi-eye-fill"></i>
            </a> |
            <a href="@Url.Action("Delete", "ClientDash", new { id = item.IdFacture })" class="btn btn-danger">
                <i class="bi bi-trash"></i>
            </a>
        </td>
    </tr>
}

</table>

SpeedInvoices.Web/Views/ClientDash/FactureS.cshtml
@model IEnumerable<SpeedInvoices.Web.Models.FactureModel>

@{
    ViewBag.Title = "Liste de facture soldée";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ReferenceFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DateCreationFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MontantTtcFacture)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Etat)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Structure)
        </th>
        <th></th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.ReferenceFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DateCreationFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.MontantTtcFacture)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Etat.NomEtat)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Structure.NomStructure)
        </td>
        <td>
            <a href="@Url.Action("Details", "ClientDash", new { id = item.IdFacture })" class="btn btn-primary">
                <i class="bi bi-eye-fill"></i>
            </a> |
            <a href="@Url.Action("Delete", "ClientDash", new { id = item.IdFacture })" class="btn btn-danger">
                <i class="bi bi-trash"></i>
            </a>
        </td>
    </tr>
}

</table>

SpeedInvoices.Web/Views/ClientDash/Forgot.cshtml
@model SpeedInvoices.Web.Models.ClientModel

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Speed Invoices</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- site icon -->
    <link rel="icon" href="@Url.Content("~/Content/images/fevicon.png")" type="image/png" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.min.css")" />
    <!-- site css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/style1.css")" />
    <!-- responsive css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/responsive.css")" />
    <!-- color css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/colors.css")" />
    <!-- select bootstrap -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-select.css")" />
    <!-- scrollbar css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/perfect-scrollbar.css")" />
    <!-- custom css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/custom.css")" />
    <!-- calendar file css -->
    <link rel="stylesheet" href="@Url.Content("~/Scripts/semantic.min.css")" />
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="inner_page login">
    <div class="full_container">
        <div class="container">
            <div class="center verticle_center full_height">
                <div class="login_section">
                    <div class="logo_login">
                        <div class="center">
                            <img width="210" src="@Url.Content("~/Content/images/logo/logo.png")" alt="#" />
                        </div>
                    </div>
                    <div class="login_form">
                        @using (Html.BeginForm("Forgotten", "ClientDash", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <fieldset>
                                <div class="field">
                                    <label class="label_field">Addresse e-mail</label>
                                    @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                    @if(Model.Message != null)
                                    {
                                        <label class="text-danger">@Model.Message</label>
                                    }
                                </div>
                                <div class="field margin_0">
                                    <label class="label_field hidden">label cacher</label>
                                    <input type="submit" class="main_bt" value="Valider" />
                                    <label class="label_field hidden">label label</label>
                                    @Html.ActionLink("Retour ?", "Login", "ClientDash", new { @class = "text-primary" })
                                </div>
                            </fieldset>
                        }
                        </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <!-- wow animation -->
    <script src="@Url.Content("~/Scripts/animate.js")"></script>
    <!-- select country -->
    <script src="@Url.Content("~/Scripts/bootstrap-select.js")"></script>
    <!-- nice scrollbar -->
    <script src="@Url.Content("~/Scripts/perfect-scrollbar.min.js")"></script>
    <script>
        var ps = new PerfectScrollbar('#sidebar');
    </script>
    <!-- custom js -->
    <script src="@Url.Content("~/Scripts/custom.js")"></script>
</body>
</html>

SpeedInvoices.Web/Views/ClientDash/Login.cshtml
@model SpeedInvoices.Web.Models.ClientModel

<!DOCTYPE html>
<html lang="en">
<head>
    <!-- basic -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- mobile metas -->
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1">
    <!-- site metas -->
    <title>Speed Invoices</title>
    <meta name="keywords" content="">
    <meta name="description" content="">
    <meta name="author" content="">
    <!-- site icon -->
    <link rel="icon" href="@Url.Content("~/Content/images/fevicon.png")" type="image/png" />
    <!-- bootstrap css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap.min.css")" />
    <!-- site css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/style1.css")" />
    <!-- responsive css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/responsive.css")" />
    <!-- color css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/colors.css")" />
    <!-- select bootstrap -->
    <link rel="stylesheet" href="@Url.Content("~/Content/bootstrap-select.css")" />
    <!-- scrollbar css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/perfect-scrollbar.css")" />
    <!-- custom css -->
    <link rel="stylesheet" href="@Url.Content("~/Content/custom.css")" />
    <!-- calendar file css -->
    <link rel="stylesheet" href="@Url.Content("~/Scripts/semantic.min.css")" />
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body class="inner_page login">
    <div class="full_container">
        <div class="container">
            <div class="center verticle_center full_height">
                <div class="login_section">
                    <div class="logo_login">
                        <div class="center">
                            <img width="210" src="@Url.Content("~/Content/images/logo/logo.png")" alt="#" />
                        </div>
                    </div>
                    <div class="login_form">
                        @using (Html.BeginForm("Login", "ClientDash", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
                        {
                            <fieldset>
                                <div class="field">
                                    <label class="label_field">Addresse e-mail</label>
                                    @Html.TextBoxFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                                <div class="field">
                                    <label class="label_field">Mot de passe</label>
                                    @Html.PasswordFor(model => model.MotDePasse, new { htmlAttributes = new { @class = "form-control" } })
                                </div>
                                <div class="field">
                                    @if (Model.Message != null)
                                    {
                                        <label class="text-danger">@Model.Message</label>
                                    }
                                    <label class="label_field hidden">label cacher</label>
                                    <label class="label_field hidden">label cacher</label>
                                    <label class="form-check-label"><input type="checkbox" class="form-check-input">Souviens-toi de moi</label>
                                    @Html.ActionLink("Mot de passe oublié ?", "Forgot", "ClientDash", new { @class = "forgot" })
                                </div>
                                <div class="field margin_0">
                                    <label class="label_field hidden">label cacher</label>
                                    <input type="submit" class="main_bt" value="Se connecter" />
                                    <label class="label_field hidden">label cacher</label>
                                    <label class="label_field hidden">label cacher</label>
                                    <a href="@Url.Action("Login", "Structure")" class="text-primary" style="margin-left:auto">Êtes-vous plutôt une entreprise ?</a>
                                </div>
                            </fieldset>
                        }
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- jQuery -->
    <script src="@Url.Content("~/Scripts/jquery.min.js")"></script>
    <script src="@Url.Content("~/Scripts/popper.min.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <!-- wow animation -->
    <script src="@Url.Content("~/Scripts/animate.js")"></script>
    <!-- select country -->
    <script src="@Url.Content("~/Scripts/bootstrap-select.js")"></script>
    <!-- nice scrollbar -->
    <script src="@Url.Content("~/Scripts/perfect-scrollbar.min.js")"></script>
    <script>
        var ps = new PerfectScrollbar('#sidebar');
    </script>
    <!-- custom js -->
    <script src="@Url.Content("~/Scripts/custom.js")"></script>
</body>
</html>

SpeedInvoices.Web/Views/ClientDash/Parametre.cshtml
@model SpeedInvoices.Web.Models.ClientModel

@{
    ViewBag.Title = "Parametre";
    Layout = "~/Views/Shared/_LayoutClient.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row column1">

    @using (Html.BeginForm("Changer", "ClientDash", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <h3>Voulez-vous changer de mot de passe ?</h3>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            <label class = "control-label col-md-2">Ancien mot de passe</label>
            <div class="col-md-10">
                @Html.PasswordFor(model => model.MotDePasse, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Nouveau mot de passe</label>
            <div class="col-md-10">
                @Html.PasswordFor(model => model.NMotDePasse, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NMotDePasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <label class = "control-label col-md-2">Confirmer mot de passe</label>
            <div class="col-md-10">
                @Html.PasswordFor(model => model.NCMotDePasse, new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NCMotDePasse, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-success" />
            </div>
        </div>
    }
</div>