SpeedInvoices.Web/Controllers/GestionController.cs
using Newtonsoft.Json;
using SpeedInvoices.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SpeedInvoices.Web.Controllers
{
    public class GestionController : Controller
    {
        string LienApiCompte = "http://localhost:81/SpeedInvoices.Service/api/Structure";
        string LienClientApi = "http://localhost:81/SpeedInvoices.Service/api/Client";
        string LienProduitApi = "http://localhost:81/SpeedInvoices.Service/api/Produit";
        string LienFactureApi = "http://localhost:81/SpeedInvoices.Service/api/Facture";

        // GET: Gestion
        public async Task<ActionResult> Index()
        {
            IndexModel model = new IndexModel();
            StructureModel structure = (StructureModel)Session["utilisateur"];

            //Compter nombre clients
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<ClientModel> clients = new List<ClientModel>();
                var response = await client.GetAsync(LienClientApi + "?IdStructure=" + structure.IdStructure);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    clients = JsonConvert.DeserializeObject<IEnumerable<ClientModel>>(json);
                }
                model.NombreC = clients.Count();
            }

            //Compter nombre produits
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<ProduitModel> produits = new List<ProduitModel>();
                var response = await client.GetAsync(LienProduitApi + "?IdStructure=" + structure.IdStructure);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    produits = JsonConvert.DeserializeObject<IEnumerable<ProduitModel>>(json);
                    model.NombreP = produits.Count();
                }
                else
                    model.NombreP = structure.Produits.Count();
            }

            //Compter nombre de facture non soldée
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<FactureModel> factureNS = new List<FactureModel>();
                var response = await client.GetAsync(LienFactureApi + "?IdStructure=" + structure.IdStructure + "&IdEtat=" + 2);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    factureNS = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
                model.NombreFNS = factureNS.Count();
            }

            //Compter nombre de facture soldée
            using (HttpClient client = new HttpClient())
            {
                IEnumerable<FactureModel> factureS = new List<FactureModel>();
                var response = await client.GetAsync(LienFactureApi + "?IdStructure=" + structure.IdStructure + "&IdEtat=" + 3);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    factureS = JsonConvert.DeserializeObject<IEnumerable<FactureModel>>(json);
                }
                model.NombreFS = factureS.Count();
            }

            //Calcul des pourcentages
            model.Pc = model.NombreC;
            model.Pfns = model.NombreFNS;
            model.Pfs = model.NombreFS;
            model.Pp = model.NombreP;

            //Structure
            model.NomStructure = structure.NomStructure;
            model.AdresseStructure = structure.AdresseStructure;
            model.TelephoneStructure = structure.TelephoneStructure;
            model.Email = structure.Email;

            return View(model);
        }

        public ActionResult Parametre()
        {
            StructureModel model = (StructureModel)Session["utilisateur"];
            model.MotDePasse = null;
            return View(model);
        }

        public async Task<ActionResult> Editer(int id)
        {
            StructureModel model = new StructureModel();
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(LienApiCompte + "?id=" + id);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<StructureModel>(json);
                }
            }

            return View("Edit", model);
        }

        [HttpPost]
        // Ne marche pas !! pour editer les infos d'une structure a partir des parametres.
        public async Task<ActionResult> Editer(StructureModel model)
        {
            try
            {
                StructureModel structureModel = (StructureModel)Session["utilisateur"];
                model.IdStructure = structureModel.IdStructure;/*
                model.DateCreationStructure = structureModel.DateCreationStructure;
                model.MotDePasse = structureModel.MotDePasse;*/

                MultipartFormDataContent multipart = new MultipartFormDataContent();
                if (ModelState.IsValid)
                {
                    var json = JsonConvert.SerializeObject(model);
                    StringContent content = new StringContent
                    (
                        json,
                        Encoding.UTF8,
                        "application/json"
                    );
                    multipart.Add(content, "data");

                    if (model.Image.ContentLength > 0)
                    {
                        byte[] picture = new byte[model.Image.ContentLength];
                        model.Image.InputStream.Read(picture, 0, picture.Length);
                        ByteArrayContent byteContent = new ByteArrayContent(picture);
                        multipart.Add(byteContent, "picture", model.Image.FileName);
                    }

                    using (HttpClient client = new HttpClient())
                    {
                        HttpResponseMessage response;
                        if (model.IdStructure == 0)
                        {
                            response = await client.PostAsync(LienApiCompte, multipart);
                        }
                        else
                        {
                            response = await client.PutAsync(LienApiCompte, multipart);
                        }

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index");
                        else
                            ModelState.AddModelError("", await response.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View("Edit", model);
        }

        [HttpPost]
        // Ne marche pas !! ca ne change pas le mot de passe.
        public async Task<ActionResult> Changer(StructureModel model)
        {
            try
            {
                StructureModel structureModel = (StructureModel)Session["utilisateur"];
                model = structureModel;
                if (ModelState.IsValid)
                {
                    using (HttpClient client = new HttpClient())
                    {
                        HttpResponseMessage response = await client.GetAsync(LienApiCompte + "?IdStructure" + model.IdStructure + "&NMotDePasse=" + model.NMotDePasse);

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index");
                        else
                            ModelState.AddModelError("", await response.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View("Parametre", model);
        }
    }
}

SpeedInvoices.Web/Views/Gestion/Edit.cshtml
@model SpeedInvoices.Web.Models.StructureModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

@using (Html.BeginForm("Editer", "Gestion", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>StructureModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.NomStructure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomStructure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomStructure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.TelephoneStructure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TelephoneStructure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TelephoneStructure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdresseStructure, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdresseStructure, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdresseStructure, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" accept="image/*" multiple="multiple" id="@Html.IdFor(x=> x.Image)" name="@Html.IdFor(x=> x.Image)" class="form-control" />
                @Html.ValidationMessageFor(model => model.Image, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SpeedInvoices.Web/Views/Gestion/Index.cshtml
@model SpeedInvoices.Web.Models.IndexModel
@{
    ViewBag.Title = "Dashboard";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row column1">
    <div class="col-md-6 col-lg-3">
        <div class="full counter_section margin_bottom_30">
            <div class="couter_icon">
                <div>
                    <i class="fa fa-user red_color"></i>
                </div>
            </div>
            <div class="counter_no">
                <div>
                    <p class="total_no">@Model.NombreC.ToString()</p>
                    <p class="head_couter">Client</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="full counter_section margin_bottom_30">
            <div class="couter_icon">
                <div>
                    <i class="bi bi-receipt-cutoff blue1_color"></i>
                </div>
            </div>
            <div class="counter_no">
                <div>
                    <p class="total_no">@Model.NombreFNS.ToString()</p>
                    <p class="head_couter">Facture non soldée</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="full counter_section margin_bottom_30">
            <div class="couter_icon">
                <div>
                    <i class="bi bi-receipt-cutoff blue2_color"></i>
                </div>
            </div>
            <div class="counter_no">
                <div>
                    <p class="total_no">@Model.NombreFS.ToString()</p>
                    <p class="head_couter">Facture soldée</p>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-6 col-lg-3">
        <div class="full counter_section margin_bottom_30">
            <div class="couter_icon">
                <div>
                    <i class="bi bi-layers-fill purple_color2"></i>
                </div>
            </div>
            <div class="counter_no">
                <div>
                    <p class="total_no">@Model.NombreP.ToString()</p>
                    <p class="head_couter">Produit</p>
                </div>
            </div>
        </div>
    </div>

    <div class="full price_table padding_infor_info">
        <div class="row">
            <!-- user profile section -->
            <!-- profile image -->
            <div class="col-lg-12">
                <div class="full dis_flex center_text">
                    <div class="profile_img"><img width="180" class="rounded-circle" src="@Session["LogoStructure"].ToString()" alt="#" /></div>
                    <div class="profile_contant">
                        <div class="contact_inner">
                            <h3>@Model.NomStructure.ToString()</h3>
                            <p><strong>Adresse: </strong>@Model.AdresseStructure.ToString()</p>
                            <ul class="list-unstyled">
                                <li><i class="fa fa-envelope-o"></i> : @Model.Email.ToString()</li>
                                <li><i class="fa fa-phone"></i> : @Model.TelephoneStructure.ToString()</li>
                            </ul>
                        </div>
                        <div class="user_progress_bar">
                            <div class="progress_bar">
                                <!-- Skill Bars -->
                                <span class="skill">Clients </span>
                                <br />
                                <span class="info_valume">@Model.Pc.ToString()%</span>
                                <div class="progress skill-bar ">
                                    <div class="progress-bar progress-bar-animated progress-bar-striped" role="progressbar" aria-valuenow="@Model.Pc.ToString()" aria-valuemin="0" aria-valuemax="50" style="width: @Model.Pc.ToString()%;">
                                    </div>
                                </div>

                                <span class="skill">Factures non soldées </span>
                                <br />
                                <span class="info_valume">@Model.Pfns.ToString()%</span>
                                <div class="progress skill-bar">
                                    <div class="progress-bar progress-bar-animated progress-bar-striped" role="progressbar" aria-valuenow="@Model.Pfns.ToString()" aria-valuemin="0" aria-valuemax="50" style="width: @Model.Pfns.ToString()%;">
                                    </div>
                                </div>

                                <span class="skill">Facture soldées </span>
                                <br />
                                <span class="info_valume">@Model.Pfs.ToString()%</span>
                                <div class="progress skill-bar">
                                    <div class="progress-bar progress-bar-animated progress-bar-striped" role="progressbar" aria-valuenow="@Model.Pfs.ToString()" aria-valuemin="0" aria-valuemax="50" style="width: @Model.Pfs.ToString()%;">
                                    </div>
                                </div>

                                <span class="skill">Produits </span>
                                <br />
                                <span class="info_valume">@Model.Pp.ToString()%</span>
                                <div class="progress skill-bar">
                                    <div class="progress-bar progress-bar-animated progress-bar-striped" role="progressbar" aria-valuenow="@Model.Pp.ToString()" aria-valuemin="0" aria-valuemax="50" style="width: @Model.Pp.ToString()%;">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

    <div class="container-fluid">
        <div class="footer">
            <p>Copyright © 2021. All rights reserved.</p>
        </div>
    </div>
</div>

SpeedInvoices.Web/Views/Gestion/Parametre.cshtml
@model SpeedInvoices.Web.Models.StructureModel

@{
    ViewBag.Title = "Parametre";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row column1" style="display:block">
    <a href="@Url.Action("Editer", "Gestion", new { id = Session["id"].ToString() })" class="btn btn-primary">Editer les informations de votre structure</a>
    <label class="label_field hidden">label cacher</label>
    <label class="label_field hidden">label cacher</label>

    @using (Html.BeginForm("Changer", "Gestion", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        
        <div class="form-horizontal">
            <h3>Voulez-vous changer de mot de passe ?</h3>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                <label class = "control-label col-md-2">Ancien mot de passe</label>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.MotDePasse, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.MotDePasse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class = "control-label col-md-2">Nouveau mot de passe</label>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.NMotDePasse, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NMotDePasse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <label class = "control-label col-md-2">Confirmer mot de passe</label>
                <div class="col-md-10">
                    @Html.PasswordFor(model => model.NCMotDePasse, new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.NCMotDePasse, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                </div>
            </div>
        </div>
    }
</div>