SpeedInvoices.Web/Controllers/CategorieController.cs
using Newtonsoft.Json;
using SpeedInvoices.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SpeedInvoices.Web.Controllers
{
    public class CategorieController : Controller
    {
        string LienCategorieApi = "http://localhost:81/SpeedInvoices.Service/api/Categorie";
        
        // GET: Categorie
        public async Task<ActionResult> Index()
        {
            IEnumerable<CategorieModel> model = new List<CategorieModel>();
            StructureModel structure = (StructureModel)Session["utilisateur"];
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(LienCategorieApi + "?IdStructure=" + structure.IdStructure);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<IEnumerable<CategorieModel>>(json);
                }
            }
            return View(model);
        }

        public ActionResult Create()
        {
            CategorieModel model = new CategorieModel();

            StructureModel structure = (StructureModel)Session["utilisateur"];
            model.IdStructure = structure.IdStructure;
            model.Structure = structure;

            return View("Edit", model);
        }

        public async Task<ActionResult> Edit(int id)
        {
            CategorieModel model = new CategorieModel();
            using (HttpClient client = new HttpClient())
            {
                var response = await client.GetAsync(LienCategorieApi + "?id=" + id);
                if (response.IsSuccessStatusCode)
                {
                    var json = await response.Content.ReadAsStringAsync();
                    model = JsonConvert.DeserializeObject<CategorieModel>(json);
                }
            }
            return View(model);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(CategorieModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var json = JsonConvert.SerializeObject(model);
                    StringContent content = new StringContent
                    (
                        json,
                        Encoding.UTF8,
                        "application/json"
                    );

                    using (HttpClient client = new HttpClient())
                    {
                        HttpResponseMessage response;
                        if (model.IdCategorie == 0)
                        {
                            response = await client.PostAsync(LienCategorieApi, content);
                        }
                        else
                        {
                            response = await client.PutAsync(LienCategorieApi, content);
                        }

                        if (response.IsSuccessStatusCode)
                            return RedirectToAction("Index");
                        else
                            ModelState.AddModelError("", await response.Content.ReadAsStringAsync());
                    }
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }

            return View(model);
        }

        public async Task<ActionResult> Delete(int id)
        {
            using (HttpClient client = new HttpClient())
            {
                var response = await client.DeleteAsync(LienCategorieApi + "?id=" + id);
            }
            return RedirectToAction("Index");
        }
    }
}

SpeedInvoices.Web/Views/Categorie/Edit.cshtml
@model SpeedInvoices.Web.Models.CategorieModel

@{
    ViewBag.Title = "EDITER UNE CATEGORIE";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row colum1">
    @using (Html.BeginForm("Edit", "Categorie", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @Html.AntiForgeryToken()
        @Html.HiddenFor(x => x.IdCategorie)
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.NomCategorie, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NomCategorie, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NomCategorie, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @*@Html.LabelFor(model => model.IdStructure, htmlAttributes: new { @class = "control-label col-md-2" })*@
                <div class="col-md-10">
                    <input type="text" value="@Model.IdStructure" name="@Html.IdFor(model => model.IdStructure)" class="form-control" readonly hidden />
                    <input type="text" value="@Model.Structure" name="@Html.IdFor(model => model.Structure)" class="form-control" readonly hidden />
                    @Html.ValidationMessageFor(model => model.IdStructure, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    }
</div>

SpeedInvoices.Web/Views/Categorie/Index.cshtml
@model IEnumerable<SpeedInvoices.Web.Models.CategorieModel>

@{
    ViewBag.Title = "LISTES DES CATEGORIES DE PRODUITS";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row column_title">
    <div class="col-md-12">
        <div class="page_title">
            <h2>@ViewBag.Title</h2>
        </div>
    </div>
</div>

<div class="row colum1">
    <table class="table table-striped">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NomCategorie)
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.NomCategorie)
                </td>
                <td>
                    <a href="@Url.Action("Edit", new { id = item.IdCategorie })" class="btn btn-primary">
                        <i class="bi bi-pencil-square"></i>
                    </a> |
                    <a href="@Url.Action("Delete", new { id = item.IdCategorie })" class="btn btn-danger">
                        <i class="bi bi-trash"></i>
                    </a>
                </td>
            </tr>
        }

    </table>
</div>